### ISSUE TITLE
Information in Packages tab not being populated/updated when triggering builds using Copr CLI

### ISSUE THREAD

**Issue by penguinpee** [fedora-copr/copr#3214] opened 2024-04-10 16:39 UTC
In a [Copr repo](https://copr.fedorainfracloud.org/coprs/gui1ty/pynose/packages/) I set up for some semi-automated smoke testing of packages against a new package, I observed that the information in the _Last Build ..._ columns in the _Packages_ tab is not being updated.

I triggered (almost) all actions from the terminal using `copr` commands, e.g. `create`, `add-package-distgit`, `build-package`. I'm running `copr-cli-1.111` on Fedora 39.

![copr_missing_info_packages_tab](https://github.com/fedora-copr/copr/assets/98259694/131aade2-e693-4d23-bdc9-761e7125cb6a)

My [cross check repo](https://copr.fedorainfracloud.org/coprs/gui1ty/nose/packages/), also set up, populated and driven from `copr-cli` looks the same.

**Comment by praiskup** [comment] 2024-04-11 07:54
Thank you for the report, @penguinpee 

The thing is that you build into a separate directory, while the page (silently) shows only the builds related to the "main" directory (i.e. builds from `pynose`, not `pynose:custom:isolated`).

This is slightly related to #3192.

**Comment by penguinpee** [comment] 2024-04-11 08:50
I see. That would indeed explain it. I learned that trick from Miro himself. I shall suffer the consequences. :wink:

**Comment by FrostyX** [comment] 2024-04-17 12:07
So I think this can be closed as a duplicate of #3192?

**Comment by nikromen** [comment] 2024-04-19 15:07
thanks for the confirmation! closing as duplicate then

**Closed by nikromen** 2024-04-19 15:07 UTC
