### ISSUE TITLE
DNF command fails with no log

### ISSUE THREAD

**Issue by fberat** [fedora-copr/copr#2458] opened 2023-01-06 18:32 UTC
The following build fails with no useful explanation from the build logs:

https://copr.fedorainfracloud.org/coprs/fberat/gcc-13_smoketest/build/5204890/

From the build log, it can be seen that: "WARNING: Dnf command failed, retrying, attempt #3, sleeping 10s"
Yet no ouput shows the DNF failure itself.

It is worth to notice that:
- This build is made in the context of GCC-13 testing phase. Which means that there is an external repository added for the build, specifically: https://jakub.fedorapeople.org/fedora-gcc13-aarch64/ 
- The build "reliably" fails, multiple trials were made with the same result, but only for aarch64. Other arches were built with no issues
- A mock build (on a dedicated aarch64 machine) was successful. The mock build made use of the copr config files (child.cfg extracted from config.tar.gz): i.e. "mock -r /home/fberat/config/child.cfg libtool-2.4.7-2.fc38.src.rpm"  builds successfully.

**Comment by codonell** [comment] 2023-01-10 14:49
This issue impacts the GNUToolchainF38 system-wide change request (https://fedoraproject.org/wiki/Changes/GNUToolchainF38) since we are using copr to mass prebuild the distribution and identify issues that need resolving for the release.

**Comment by praiskup** [comment] 2023-01-10 15:39
Thank you for the report @fberat. Since there's no relevant output from
DNF it seems like some ugly crash.  I is a pity we don't see the exit
status at least to better understand what is going on (segfault or so), so
I filled a [Mock
issue](https://github.com/rpm-software-management/mock/issues/1022), ideas
are welcome.

> A mock build (on a dedicated aarch64 machine) was successful. 

Copr uses dedicated virtual Fedora 37 machines (no parallel builds on the
same hosts, compared to the Fedora Koji deployment).

Would you mind reproducing and debugging the problem yourself, if I gave
you the ssh access to one of our aarch64 builders?  These are Graviton3
machines in AWS.

**Comment by praiskup** [comment] 2023-01-10 15:48
Thank you!  Cool, I handed over one machine to Frédéric, going to deallocate it tomorrow.

**Comment by fberat** [comment] 2023-01-10 16:48
@praiskup it looks like the DNF version within the chroot gnerates a SEGFAULT. That puzzles me, as I couldn't reproduce that issue on a dedicated aarch64 machine. I wonder what makes the environment different that DNF crashes here.

**Comment by praiskup** [comment] 2023-01-25 06:18
I suppose this has been fixed by an [updated GCC](https://gcc.gnu.org/PR107678) package. Feel free to reopen if I'm wrong.

**Closed by praiskup** 2023-01-25 06:18 UTC
Labels: bug
