### ISSUE TITLE
Bootstrap circular dependencies

### ISSUE THREAD

**Issue by xambroz** [fedora-copr/copr#3272] opened 2024-05-20 16:52 UTC
Hello,
this is rather feature request than bug report. 
It is related to attempt to implement and rebuild in COPR the bootstrapping according the guide from:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#bootstrapping

It would be nice when using the cli copr utility to be able to pass some custom set of arguments for the rpmbuild for the particular build of the package. Specifically I would like to be able to pass "--with bootstrap" to the consequent builds of packages in the same copr repository.

I have tried "copr build package --bootstrap on", but it didn't do what I expect it to do. 

I am maintaining couple of packages, which are having some circular dependencies. To resolve I would like to do something like this:
```
rpmbuild -ba libuna.spec --with bootstrap     # builds base libuna library
rpmbuild -ba libcfile.spec                                   # builds libcfile library depending on libuna
rpmbuild -ba libuna.spec                                    # rebuilds libuna library + unatools subpackage depending on libcfile
```

-------- Workaround from GUI is 
- Settings / Project Details / 2. Build options
- go through all enabled chroots and click the "Edit" button on each enabled chroot
- add "bootstrap" to "With options"
- rebuild bootstrapped library lib1
- change back
- rebuild depending lib2
- rebuild the lib1 with the circle dependency

**Comment by FrostyX** [comment] 2024-05-23 15:17
Thank you for the report @xambroz,
I will close this as a duplicate of #2541 that you mentioned.

The issue references several other tickets describing workflows and missing parameters, similar to this one. Whoever is going to be implementing the solution will go through all the referenced tickets and make sure it applies to them.

**Closed by FrostyX** 2024-05-23 15:17 UTC
