### ISSUE TITLE
ISE - AttributeError: 'NoneType' object has no attribute 'module_setup_commands'

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#3059] opened 2023-12-13 11:10 UTC
I have seen this in Fedora's Copr log

```
[Wed Dec 13 10:16:28.431539 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] ERROR:coprs:Admin-only exception
[Wed Dec 13 10:16:28.431562 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] Request: GET https://copr.fedorainfracloud.org/backend/get-build-task/6734728-fedora-37-s390x 
[Wed Dec 13 10:16:28.431571 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] User: None
[Wed Dec 13 10:16:28.431579 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] Traceback (most recent call last):
[Wed Dec 13 10:16:28.431587 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
[Wed Dec 13 10:16:28.431620 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]     rv = self.dispatch_request()
[Wed Dec 13 10:16:28.431628 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]          ^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:16:28.431637 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
[Wed Dec 13 10:16:28.431645 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Wed Dec 13 10:16:28.431653 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:16:28.431661 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]   File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 361, in get_build_task
[Wed Dec 13 10:16:28.431668 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]     build_record = get_build_record(task)
[Wed Dec 13 10:16:28.431676 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]                    ^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:16:28.431684 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]   File "/usr/share/copr/coprs_frontend/coprs/views/backend_ns/backend_general.py", line 172, in get_build_record
[Wed Dec 13 10:16:28.431692 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]     modules = copr_chroot.module_setup_commands
[Wed Dec 13 10:16:28.431700 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[Wed Dec 13 10:16:28.431707 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] AttributeError: 'NoneType' object has no attribute 'module_setup_commands'
[Wed Dec 13 10:16:28.431862 2023] [wsgi:error] [pid 1880880:tid 1880894] [remote 52.70.240.171:11306] ERROR:coprs:Response error: 500 Request wasn't successful, there is probably a bug in the Copr code.
```

**Comment by xsuchy** [comment] 2023-12-13 11:12
Note: this is very frequent ISE.

**Comment by FrostyX** [comment] 2023-12-13 12:15
Thank you for the report @xsuchy,
I am closing as a duplicate of #2759 which we have in 3 months plan.

**Closed by FrostyX** 2023-12-13 12:15 UTC
