### ISSUE TITLE
Running builds should recover from builder crash

### ISSUE THREAD

**Issue by FrostyX** [fedora-copr/copr#2934] opened 2023-09-30 21:07 UTC
We have some long-running builds in ppc64le chroots. They are in the `running` state, backend shows their corresponding process, e.g.

```
2898926 ?        Sl    42:32 Builder for task 6402587-fedora-37-ppc64le: Job 6402587-fedora-37-ppc64le, host info: ResallocHost, ticket_id=4188640, hostname=2620:52:3:1:dead:beef:cafe:c216 (command: /usr/bin/copr-backend-process-build --daemon --build-id 6402587 --chroot fedora-37-ppc64le --worker-id rpm_build_worker:6402587-fedora-37-ppc64le)
```

but the builder instance is dead.

I wanted to switch them back to the pending state so that backend can pick them up again and use a new builder for them but I don't know how. Killing the process fails the build, and closing the ticket does nothing. Do we have a known workaround for this?

Also, we should implement some live-check to do this automatically.

**Comment by praiskup** [comment] 2023-10-02 08:21
This looks like a duplicate of #2888.  Copr would restart the build if the SSH connection was dead.

**Closed** 2023-10-02 11:24 UTC
