### ISSUE TITLE
copr Fedora 40 x86_64 rpmbuild binary broken

### ISSUE THREAD

**Issue by nestire** [fedora-copr/copr#3435] opened 2024-09-30 15:16 UTC
my Build fails with: 
/usr/bin/rpmbuild: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory

build with fedora 41 and fedora 39 works 

[builder-live.log](https://github.com/user-attachments/files/17192247/builder-live.log)

**Comment by FrostyX** [comment] 2024-10-07 10:32
It's strange though. When I build the package using Mock, it works.

```
mock -r fedora-40-x86_64 nitrokey-app2-2.3.2-1.src.rpm --enable-net
```

But when I try to build it using copr-rpmbuild, it fails

```
copr-rpmbuild --verbose --drop-resultdir --task-url https://copr.fedorainfracloud.org/backend/get-build-task/8092164-fedora-40-x86_64 --chroot fedora-40-x86_64
```

Even though with a different error than OP

```
/bin/sh: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

**Comment by praiskup** [comment] 2024-10-07 12:24
Issues like this often happen when some package provides duplicate soname to the one provided by core system.  Isn't libpcap.so provided (by mistake) by ` nitrokey-app2`?

**Comment by mmerklinger** [comment] 2024-10-15 10:42
Indeed we provided a duplicate of `libcap.so`. I'm currently looking into building the package without _pyinstaller_. We recently did some changes to reduce dependencies. The dependencies were the original reason to build it with _pyinstaller_. I think we can close this issue.

**Comment by praiskup** [comment] 2024-10-15 12:06
Thank you for the update. Closing.

**Closed by praiskup** 2024-10-15 12:06 UTC
