### ISSUE TITLE
copr can't handle http source download

### ISSUE THREAD

**Issue by musuruan** [fedora-copr/copr#3079] opened 2023-12-24 11:31 UTC
Some examples:
https://download.copr.fedorainfracloud.org/results/musuruan/cbm/srpm-builds/06812356/builder-live.log.gz

```
[lookaside]
download_url = https://${git_props:remote_netloc}/repo/pkgs/%(repo_path)s/%(filename)s/%(hashtype)s/%(hash)s/%(filename)s

Writing config into /var/lib/copr-rpmbuild/workspace/workdir-t67ptl_d/.config/rpkg.conf
Running: rpkg srpm --outdir /var/lib/copr-rpmbuild/results --spec /var/lib/copr-rpmbuild/workspace/workdir-t67ptl_d/fedora-rpms/cgterm

cmd: ['rpkg', 'srpm', '--outdir', '/var/lib/copr-rpmbuild/results', '--spec', '/var/lib/copr-rpmbuild/workspace/workdir-t67ptl_d/fedora-rpms/cgterm']
cwd: /var/lib/copr-rpmbuild/workspace/workdir-t67ptl_d/fedora-rpms/cgterm
rc: 1
stdout: Wrote: /var/lib/copr-rpmbuild/results/cgterm.spec
stderr: warning: Downloading http://paradroid.automac.se/cgterm/cgterm-1.6.tar.gz to /var/lib/copr-rpmbuild/results/cgterm-1.6.tar.gz
curl: (1) Protocol "http" not supported or disabled in libcurl
error: Couldn't download http://paradroid.automac.se/cgterm/cgterm-1.6.tar.gz

Copr build error: warning: Downloading http://paradroid.automac.se/cgterm/cgterm-1.6.tar.gz to /var/lib/copr-rpmbuild/results/cgterm-1.6.tar.gz
curl: (1) Protocol "http" not supported or disabled in libcurl
error: Couldn't download http://paradroid.automac.se/cgterm/cgterm-1.6.tar.gz
```

https://download.copr.fedorainfracloud.org/results/musuruan/games/srpm-builds/06812362/builder-live.log.gz

```
[lookaside]
download_url = https://${git_props:remote_netloc}/repo/pkgs/%(repo_path)s/%(filename)s/%(hashtype)s/%(hash)s/%(filename)s

Writing config into /var/lib/copr-rpmbuild/workspace/workdir-s1gevu74/.config/rpkg.conf
Running: rpkg srpm --outdir /var/lib/copr-rpmbuild/results --spec /var/lib/copr-rpmbuild/workspace/workdir-s1gevu74/fedora-rpms/biniax2

cmd: ['rpkg', 'srpm', '--outdir', '/var/lib/copr-rpmbuild/results', '--spec', '/var/lib/copr-rpmbuild/workspace/workdir-s1gevu74/fedora-rpms/biniax2']
cwd: /var/lib/copr-rpmbuild/workspace/workdir-s1gevu74/fedora-rpms/biniax2
rc: 1
stdout: Wrote: /var/lib/copr-rpmbuild/results/biniax2.spec
stderr: warning: Downloading http://www.tuzsuzov.com/biniax/biniax2-1.30-fullsrc.tar.gz to /var/lib/copr-rpmbuild/results/biniax2-1.30-fullsrc.tar.gz
curl: (1) Protocol "http" not supported or disabled in libcurl
error: Couldn't download http://www.tuzsuzov.com/biniax/biniax2-1.30-fullsrc.tar.gz

Copr build error: warning: Downloading http://www.tuzsuzov.com/biniax/biniax2-1.30-fullsrc.tar.gz to /var/lib/copr-rpmbuild/results/biniax2-1.30-fullsrc.tar.gz
curl: (1) Protocol "http" not supported or disabled in libcurl
error: Couldn't download http://www.tuzsuzov.com/biniax/biniax2-1.30-fullsrc.tar.gz
```

https URLs are fine instead.

**Comment by sharkcz** [comment] 2023-12-27 21:54
I believe `http` downloads are not allowed by design.

**Comment by praiskup** [comment] 2024-01-02 08:59
Thank you for the report.

> I believe http downloads are not allowed by design.¨

Yes, [indeed](https://github.com/fedora-copr/copr/blob/82f431d08a474b182800e0361aca32c70403c689/rpmbuild/copr_rpmbuild/helpers.py#L179) - the whitelist ends up [here](https://github.com/fedora-copr/copr/blob/82f431d08a474b182800e0361aca32c70403c689/rpmbuild/copr_rpmbuild/helpers.py#L377). It has a transitive effect on RPM and the called curl logic.

Since this is a bug report and not an RFE, I'm closing as "not a bug".

**Closed by praiskup** 2024-01-02 08:59 UTC
