### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Enchufa2** [fedora-copr/copr#3217] opened 2024-04-13 09:16 UTC
A workflow failed some hours ago, and since then I see this, e.g.:

```
$ copr-cli build-package --nowait  --with-build-id 7305174 -r fedora-38-x86_64 -r fedora-39-x86_64 -r fedora-40-x86_64 -r fedora-rawhide-x86_64 cran --name R-CRAN-xfun

Something went wrong:
Error: Database error, contact admin
```

This is after starting build 7305174. And the command works fine without ` --with-build-id 7305174`.

**Comment by FrostyX** [comment] 2024-04-13 09:29
Thank you for the report @Enchufa2,
I am seeing some tracebacks in the logs:

This one is yours:

```
Request: POST https://copr.fedorainfracloud.org/api_3/package/build
User: iucar
Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1704, in _execute_20
    meth = statement._execute_on_connection
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 345, in check_if_api_login_is_required
    return endpoint_method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flask_restx/marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/apiv3_ns/apiv3_packages.py", line 294, in post
    build = PackagesLogic.build_package(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/packages_logic.py", line 337, in build_package
    build = builds_logic.BuildsLogic.create_new(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 754, in create_new
    build = cls.add(
            ^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 884, in add
    batch = cls._setup_batch(batch, after_build_id, with_build_id, user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/builds_logic.py", line 791, in _setup_batch
    batch = BatchesLogic.get_batch_or_create(with_build_id, user, True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/batches_logic.py", line 79, in get_batch_or_create
    with locked_table("batch", "for_build_id={}".format(build_id)):
  File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/batches_logic.py", line 44, in locked_table
    _lock_table(table_name)
  File "/usr/lib/python3.12/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/logic/batches_logic.py", line 32, in _lock_table
    connection.execute("LOCK TABLE {} IN EXCLUSIVE MODE;".format(
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/future/engine.py", line 286, in execute
    return self._execute_20(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/engine/base.py", line 1706, in _execute_20
    util.raise_(
  File "/usr/lib64/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'LOCK TABLE batch IN EXCLUSIVE MODE;'
```

Seems to be caused by migrating the package-rebuild endpoint to flask-restx. I am going to take a look ASAP.

**Comment by FrostyX** [comment] 2024-04-13 09:52
Ah, this has nothing to do with flask-restx but rather SQLAlchemy 2.0 support that I've been working on. The issue can be fixed with:

```diff
--- a/frontend/coprs_frontend/coprs/logic/batches_logic.py
+++ b/frontend/coprs_frontend/coprs/logic/batches_logic.py
@@ -8,6 +8,7 @@ import backoff

 from sqlalchemy.exc import SQLAlchemyError
 from sqlalchemy_utils.functions import quote as sa_quote
+from sqlalchemy.sql import text
 from coprs import app, db, cache
 from coprs.helpers import WorkList
 from coprs.models import Batch, Build
@@ -29,8 +30,8 @@ def _lock_table(table):
     # (while reading is not blocked) until the end of the transaction
     # (commit / rollback)
     with db.engine.connect() as connection:
-        connection.execute("LOCK TABLE {} IN EXCLUSIVE MODE;".format(
-            sa_quote(db.engine, table),
+        connection.execute(text("LOCK TABLE {} IN EXCLUSIVE MODE;".format(
+            sa_quote(db.engine, table)),
         ))
```

I am going to send a PR and hotfix this in production.

**Comment by FrostyX** [comment] 2024-04-13 10:07
Hotfixed. @Enchufa2 can you please try if it works for you now?

**Comment by Enchufa2** [comment] 2024-04-14 08:28
It works fine now, thanks for the quick fix!

**Closed** 2024-04-15 07:17 UTC
