### ISSUE TITLE
AttributeError: 'Package' object has no attribute 'latest_build'

### ISSUE THREAD

**Issue by xsuchy** [fedora-copr/copr#2917] opened 2023-09-18 08:21 UTC
I have seen this in frontend log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 245, in wrapper
    return f(copr, **kwargs)
           ^^^^^^^^^^^^^^^^^
  File "/usr/share/copr/coprs_frontend/coprs/views/coprs_ns/coprs_packages.py", line 84, in copr_package_icon
    return send_build_icon(package.latest_build, no_cache=True)
                           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Package' object has no attribute 'latest_build'
```

**Comment by FrostyX** [comment] 2023-12-20 13:53
Closing as duplicate of #3057

**Closed by FrostyX** 2023-12-20 13:53 UTC
Labels: bug
