### ISSUE TITLE
package in openEuler has wrong GPG key

### ISSUE THREAD

**Issue by pkking** [fedora-copr/copr#2413] opened 2022-12-01 02:19 UTC
For https://github.com/rpm-software-management/mock/pull/964, openEuler 22.03 LTS and openEuler 20.03 LTS already have a mock config(only for x64_64 and aarch64) and GPG-KEYs
Can we create the corresponding chroot now?

**Comment by praiskup** [comment] 2022-12-03 16:19
Thanks for your ticket.

Are you requesting new chroots inside Fedora Copr https://copr.fedorainfracloud.org/ ?  In your own Copr deployment you can create them quite easily, using `copr-frontend create-chroot`.

**Comment by pkking** [comment] 2022-12-04 04:53
Yes, want to add in offical copr instance.

**Comment by praiskup** [comment] 2022-12-05 09:23
I think we need `openeuler.png` file [here](https://github.com/fedora-copr/copr/tree/74f7586a90bfce30fa4dbe54120532270a5c1bf9/frontend/coprs_frontend/coprs/static).

**Comment by pkking** [comment] 2022-12-05 09:50
Ok, i will try it in a PR :)

**Comment by praiskup** [comment] 2022-12-05 15:57
@nikromen is working on processing this

**Comment by nikromen** [comment] 2022-12-14 15:04
Hello @pkking 
we've just enabled chroots for openeuler 22.03. 

You are also requesting openEuler 20.03 chroots in this issue, but I can see that GPG keys are available only for version 22.03. See https://github.com/xsuchy/distribution-gpg-keys/pull/73 and no key for openeuler 20.03 was added

This will cause GPG check error for 20.03 chroots https://download.copr.fedorainfracloud.org/results/frostyx/opensuse-old/openeuler-20.03-x86_64/05144316-copr-cli/builder-live.log.gz (at the bottom of the log)

So we would firstly need to add the key for openeuler 20.03 to create these chroots

**Comment by FrostyX** [comment] 2022-12-14 18:27
Copy-pasting the error message here, so we don't lose it.

```
GPG key at file:///usr/share/distribution-gpg-keys/openeuler/RPM-GPG-KEY-openEuler (0xB25E7F66) is already installed
The GPG keys listed for the "update" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: ima-evm-utils-libs-1.3.1-4.oe1.x86_64
 GPG Keys are configured as: file:///usr/share/distribution-gpg-keys/openeuler/RPM-GPG-KEY-openEuler
Error: GPG check FAILED
```

**Comment by pkking** [comment] 2022-12-15 03:22
Thanks, i will fix it in mock then.

**Comment by praiskup** [comment] 2022-12-15 09:21
More precisely, it seems the distribution-gpg-keys package needs fixing.

**Comment by xsuchy** [comment] 2022-12-19 12:05
Nope. The problem is somewhere else:
```
$ sudo rpm --import /usr/share/distribution-gpg-keys/openeuler/RPM-GPG-KEY-openEuler
$ LC_ALL=C rpm -K ./mock/openeuler-20.03-x86_64-bootstrap/dnf_cache/update-d9e3303793a15bad/packages/ima-evm-utils-libs-1.3.1-4.oe1.x86_64.rpm
./mock/openeuler-20.03-x86_64-bootstrap/dnf_cache/update-d9e3303793a15bad/packages/ima-evm-utils-libs-1.3.1-4.oe1.x86_64.rpm: digests SIGNATURES NOT OK

$ rpm -pqi ./mock/openeuler-20.03-x86_64-bootstrap/dnf_cache/update-d9e3303793a15bad/packages/ima-evm-utils-libs-1.3.1-4.oe1.x86_64.rpm |grep Signature
varování: ./mock/openeuler-20.03-x86_64-bootstrap/dnf_cache/update-d9e3303793a15bad/packages/ima-evm-utils-libs-1.3.1-4.oe1.x86_64.rpm: Hlavička V3 RSA/SHA1 Signature, key ID 911a4386: NOKEY
Signature   : RSA/SHA1, St 1. prosince 2021, 08:33:03, Key ID a30b7011911a4386


$ rpm -pqi ./mock/openeuler-20.03-x86_64-bootstrap/dnf_cache/update-d9e3303793a15bad/packages/bash-5.0-13.oe1.x86_64.rpm |grep Signature
Signature   : RSA/SHA1, St 3. června 2020, 12:53:12, Key ID d557065eb25e7f66
```
Notice the different Key ID. 

In other words - the ima-evm-utils-lib package is signed by different key than the rest of the repository. I.e. the dnf warning does exactly what it should. It warns you because of wrong gpg key.

**Comment by praiskup** [comment] 2022-12-19 19:11
I thought there was a wrong key or e.g. multiple keys. But `RSA/SHA1` really seems like some issue.

**Comment by xsuchy** [comment] 2022-12-22 06:56
I will close this one. As this needs to be resolved on the OpenEuler side. Feel free to continue in discussion here if you have some follow up questions.

**Closed by xsuchy** 2022-12-22 06:56 UTC
Labels: chroot

**Comment by praiskup** [comment] 2023-01-06 09:01
JFTR, should be fixed in Fedora Copr production with the updated mock-core-configs package:
https://bodhi.fedoraproject.org/updates/?search=mock-core-configs
